### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by marcinmierzejewski1024** [BLSSwiftHackaton2015/Pomodoro#1]
I got build failed when i try to build and run project, some methods are not defined:

Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:36:14: error: 'UIScrollView' does not have a member named 'setTranslatesAutoresizingMaskIntoConstraints'
        self.scrollView.setTranslatesAutoresizingMaskIntoConstraints(false)
             ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:41:56: error: cannot invoke 'constraintsWithVisualFormat' with an argument list of type '(String, options: nil, metrics: nil, views: [String : UIScrollView!])'
        let horizontalConstraints = NSLayoutConstraint.constraintsWithVisualFormat("H:|-(0)-[scrollView]-(0)-|", options: nil, metrics: nil, views: ["scrollView": self.scrollView])
                                                       ^
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:42:54: error: cannot invoke 'constraintsWithVisualFormat' with an argument list of type '(String, options: nil, metrics: nil, views: [String : UIScrollView!])'
        let verticalConstraints = NSLayoutConstraint.constraintsWithVisualFormat("V:|-(0)-[scrollView]-(0)-|", options: nil, metrics: nil, views: ["scrollView": self.scrollView])
                                                     ^
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:54:9: error: 'UIView' does not have a member named 'setTranslatesAutoresizingMaskIntoConstraints'
        view1.setTranslatesAutoresizingMaskIntoConstraints(false)
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:59:13: error: 'UIImageView' does not have a member named 'setTranslatesAutoresizingMaskIntoConstraints'
            patternView.setTranslatesAutoresizingMaskIntoConstraints(false)
            ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:88:9: error: 'UIImageView' does not have a member named 'setTranslatesAutoresizingMaskIntoConstraints'
        lastView.setTranslatesAutoresizingMaskIntoConstraints(false)
        ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:103:9: error: 'UILabel' does not have a member named 'setTranslatesAutoresizingMaskIntoConstraints'
        label.setTranslatesAutoresizingMaskIntoConstraints(false)
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dom/Documents/Pomodoro/Pomodoro/Pomodoro/PMSlideControl.swift:129:9: error: 'UIImageView' does not have a member named 'setTranslatesAutoresizingMaskIntoConstraints'
        arrowView.setTranslatesAutoresizingMaskIntoConstraints(false)
        ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by tomkowz** [comment]
Hey @marcinmierzejewski1024, which Xcode are you using to build the app?

**Comment by marcinmierzejewski1024** [comment]
@tomkowz Version 7.0 beta (7A120f)

**Comment by tomkowz** [comment]
I belive the app was written in Xcode 6.3 and Swift 1.2. Please try with Xcode 6.3 or 6.4

**Comment by marcinmierzejewski1024** [comment]
Xcode 6.4 gives same errors : < Is there any switch to change Swift version?

**Comment by tomkowz** [comment]
App is running on Xcode 6.4. Checked a second ago. Make sure you've got no changes in the code. Check `git status` or execute `git reset --hard` to reset all the changes if any.

**Comment by marcinmierzejewski1024** [comment]
Build succeeded... thanks!

**Comment by tomkowz** [comment]
Great!
